### ISSUE TITLE
Active widget doesn't reset correctly on re-rendering

### ISSUE THREAD

**Issue by rosecers** [cosmo-epfl/chemiscope#59] opened 2020-07-07 11:41 UTC
See videos

![bug](https://user-images.githubusercontent.com/47536110/86775332-96a05880-c057-11ea-921f-438feab29366.gif)

**Comment by Luthaf** [comment] 2020-07-07 12:10
WAT

**Comment by Luthaf** [comment] 2020-07-07 12:12
Amazing bug report by the way! 

I have no idea where this can come from. This is with Chrome (which version?) on macOS, right? We should look whether this can be reproduced with other browsers.

**Comment by rosecers** [comment] 2020-07-07 12:15
Version 83.0.4103.116 on MacOS. I can try and reproduce on a different browser. (It will get Safari's hope up that I'll start using it...)

**Comment by rosecers** [comment] 2020-07-07 12:23
![bug](https://user-images.githubusercontent.com/47536110/86780701-4fb56180-c05d-11ea-981f-02979bcd2a15.gif)
The problem is in safari as well. It's got to be a code issue, not a browser issue

**Comment by Luthaf** [comment] 2020-07-07 12:55
I can also reproduce with Firefox =/ Seems to only happen with multiple viewers, so I am starting to wonder if it is related to having multiple WebGL context in the page (I remember seeing some warning a while ago regarding having more than 16 WebGL contexts).

**Comment by Luthaf** [comment] 2020-07-07 14:38
Now that #58 is merged, it looks like this is fixed

**Comment by ceriottm** [comment] 2020-07-07 16:08
this is the best. mysterious bug that gets fixed in mysterious ways.

**Closed** 2020-07-08 08:44 UTC
Labels: bug
